// <auto-generated />
using System;
using LoanApplicationAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanApplicationAPI.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanApplicationAPI.DBModels.ApplicationStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasJsonPropertyName("statusId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .HasJsonPropertyName("description");

                    b.Property<bool>("IsUpdateEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_update_enabled")
                        .HasJsonPropertyName("isUpdateEnabled");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status_code")
                        .HasJsonPropertyName("statusCode");

                    b.HasKey("StatusId");

                    b.ToTable("application_status");
                });

            modelBuilder.Entity("LoanApplicationAPI.DBModels.LoanApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_datetime")
                        .HasJsonPropertyName("createdDateTime");

                    b.Property<int>("CurrentStatusId")
                        .HasColumnType("int")
                        .HasColumnName("current_status_id")
                        .HasJsonPropertyName("currentStatusId");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("loan_amount")
                        .HasJsonPropertyName("amount");

                    b.Property<int>("LoanTypeId")
                        .HasColumnType("int")
                        .HasColumnName("loan_type_id")
                        .HasJsonPropertyName("loanTypeId");

                    b.Property<int>("PreviousStatusId")
                        .HasColumnType("int")
                        .HasColumnName("previous_status_id")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_datetime")
                        .HasJsonPropertyName("updatedDateTime");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.ToTable("loan_applications");
                });

            modelBuilder.Entity("LoanApplicationAPI.DBModels.LoanType", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("loan_id")
                        .HasJsonPropertyName("loanId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .HasJsonPropertyName("description");

                    b.Property<string>("LoanCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loan_code")
                        .HasJsonPropertyName("loanCode");

                    b.HasKey("LoanId");

                    b.ToTable("loan_types");
                });

            modelBuilder.Entity("LoanApplicationAPI.DBModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("ContactNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("contact_number")
                        .HasJsonPropertyName("contactNumber");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_datetime")
                        .HasJsonPropertyName("createdDateTime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email")
                        .HasJsonPropertyName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name")
                        .HasJsonPropertyName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name")
                        .HasJsonPropertyName("lastName");

                    b.HasKey("Id");

                    b.ToTable("users", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
